title: "Benson's Blog"
description: "Notes, projects, and writing"
url: "https://blog.bensonngu.cc"
baseurl: ""
timezone: Asia/Kuala_Lumpur
lang: en

theme: minima
markdown: kramdown

author:
  name: "Benson Ngu"
  email: "work@bensonngu.cc"
  url: "https://bensonngu.cc"

logo: "/assets/img/logo-social.png"

social:
  name: "Benson Ngu"
  links: 
    - https://github.com/BensonNgu
    - https://linkedin.com/in/bensonnguchengjie

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 10
paginate_path: "/page:num/"
collections:
  pages:
    output: true
defaults:
  - scope: {path: ""}
    values: 
      layout: default
      image: "assets/img/og.png"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Benson Ngu"
      permalink: ":title"
        

